### ISSUE TITLE
Please remove or fix this test t/16-namespace_clean.t

### ISSUE THREAD

**Issue by PaulGWebster** [celogeek/MooX-Options#70] opened 2019-10-21 19:18 UTC
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942275

> Can't locate object method "__" via package "TestNamespaceClean" at /home/paul1/.cpanm/work/1571675833.31763/MooX-Options-4.103/blib/lib/MooX/Options/Role.pm line 352.
> # Tests were run but no plan was declared and done_testing() was not seen.
> # Looks like your test exited with 255 just after 1.
> t/16-namespace_clean.t ...................... 
> Dubious, test returned 255 (wstat 65280, 0xff00)
> All 1 subtests passed

**Comment by PaulGWebster** [comment] 2019-10-21 19:21
The folks in that pastebin are not my self, but I also have that problem and am having to pin MooX::Options at 4.023 so that my tests can succeed on a larger project

**Comment by rehsack** [comment] 2019-10-21 19:23
Inpolite duplicate of https://github.com/celogeek/MooX-Options/pull/69

**Closed as completed by rehsack** 2019-10-21 19:23 UTC
